package farmacie;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.sql.PreparedStatement;
import com.sun.rowset.internal.Row;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import static javax.management.Query.lt;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;


import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartUtils;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static org.apache.commons.math3.fitting.leastsquares.LeastSquaresFactory.model;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.ss.usermodel.Sheet;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JPanel;
import org.jfree.chart.ChartFrame;
import org.apache.poi.hssf.usermodel.HSSFCell;
import static org.apache.poi.hssf.usermodel.HSSFChart.HSSFChartType.Bar;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;


public class Interfata extends javax.swing.JFrame {

    /**
     * Creates new form Interfata
     */
    
    
    Connection conn = Connect.ConecrDb();
    String idClient;
    String rolAutentificare;
    String idMedicament;
    String pretAscendent = "ascendent",pretDescendent = "descendent";
     
      
    public Interfata() {
        initComponents();
        pnl_client.setVisible(false);
        pnl_medicament.setVisible(false);
        pnl_utilizator.setVisible(false);
        panel_vanzare.setVisible(false);
        menu.setEnabled(false);
        
       this.setTitle("Farmacie");
       this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("farmacie.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_autentificare = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_parola = new javax.swing.JPasswordField();
        cmb_rol = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        pnl_client = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nume = new javax.swing.JTextField();
        txt_prenume = new javax.swing.JTextField();
        txt_varsta = new javax.swing.JTextField();
        txt_sex = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_clienti = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        pnl_medicament = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_denumire = new javax.swing.JTextField();
        txt_pret = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_medicament = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_cautare = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmb_filtrare = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        den_medicament = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        pnl_utilizator = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        parola = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        panel_vanzare = new javax.swing.JPanel();
        cmb_medicament = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_utilizator = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_autentificare.setBorder(javax.swing.BorderFactory.createTitledBorder("Autentificare"));

        jLabel1.setText("Email:");

        jLabel2.setText("Parola:");

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setText("Autentificare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Gestionar", "Farmacist" }));
        cmb_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rolActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/autentificare.png"))); // NOI18N

        javax.swing.GroupLayout pnl_autentificareLayout = new javax.swing.GroupLayout(pnl_autentificare);
        pnl_autentificare.setLayout(pnl_autentificareLayout);
        pnl_autentificareLayout.setHorizontalGroup(
            pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_autentificareLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_email)
                    .addComponent(txt_parola))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_autentificareLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(210, 210, 210))
        );
        pnl_autentificareLayout.setVerticalGroup(
            pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_autentificareLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnl_autentificareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(cmb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel3.setText("Nume:");

        jLabel4.setText("Prenume:");

        jLabel5.setText("Varsta:");

        jLabel6.setText("Sex:");

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setText("Adauga");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Modifica");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setText("Stergere");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabel_clienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_clienti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_clientiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_clienti);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/client.png"))); // NOI18N

        jLabel24.setText("Cautare(nume):");

        jButton16.setBackground(new java.awt.Color(153, 153, 255));
        jButton16.setText("Cautare");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_clientLayout = new javax.swing.GroupLayout(pnl_client);
        pnl_client.setLayout(pnl_clientLayout);
        pnl_clientLayout.setHorizontalGroup(
            pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clientLayout.createSequentialGroup()
                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_clientLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_clientLayout.createSequentialGroup()
                                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nume, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txt_prenume)
                                    .addComponent(txt_varsta)
                                    .addComponent(txt_sex)))
                            .addGroup(pnl_clientLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_clientLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_clientLayout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2)
                        .addGap(74, 74, 74)
                        .addComponent(jButton3)
                        .addGap(73, 73, 73)
                        .addComponent(jButton4)))
                .addGap(27, 27, 27))
        );
        pnl_clientLayout.setVerticalGroup(
            pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_clientLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_clientLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton16))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_clientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_varsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30))))
        );

        jLabel7.setText("Denumire:");

        jLabel8.setText("Pret:");

        tabel_medicament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_medicament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_medicamentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_medicament);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setText("Adauga");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setText("Modifica");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setText("Sterge");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Cauta(denumire):");

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setText("Cautare");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(118, 223, 246));
        jButton10.setText("Export to notepad");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel13.setText("Filtrare:");

        cmb_filtrare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pret mai mic", "Pret mai mare", "Stoc", "Producator" }));
        cmb_filtrare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_filtrareMouseClicked(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(145, 227, 81));
        jButton11.setText("Filtrare");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(237, 137, 137));
        jButton12.setText("Export PDF");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(104, 222, 144));
        jButton13.setText("Export XLS");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Grafic");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel15.setText("Data start:");

        jLabel17.setText("Data final:");

        jLabel14.setText("Denumire Medicament:");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/medicament.png"))); // NOI18N

        jLabel22.setText("Stoc");

        jLabel23.setText("Producator");

        javax.swing.GroupLayout pnl_medicamentLayout = new javax.swing.GroupLayout(pnl_medicament);
        pnl_medicament.setLayout(pnl_medicamentLayout);
        pnl_medicamentLayout.setHorizontalGroup(
            pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_medicamentLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_medicamentLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_medicamentLayout.createSequentialGroup()
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel9)
                            .addComponent(jLabel22)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_pret)
                    .addComponent(txt_denumire)
                    .addComponent(txt_cautare)
                    .addComponent(cmb_filtrare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2))
                .addGap(27, 27, 27)
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_medicamentLayout.createSequentialGroup()
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_medicamentLayout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(37, 37, 37)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_medicamentLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton6)
                                .addGap(57, 57, 57)
                                .addComponent(jButton7))))
                    .addGroup(pnl_medicamentLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_medicamentLayout.createSequentialGroup()
                                    .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel15))
                                    .addGap(79, 79, 79)
                                    .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnl_medicamentLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(den_medicament, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(254, 254, 254))
        );
        pnl_medicamentLayout.setVerticalGroup(
            pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_medicamentLayout.createSequentialGroup()
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_medicamentLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_denumire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_pret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cautare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(pnl_medicamentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton10)
                    .addComponent(jButton13))
                .addGap(13, 13, 13)
                .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_medicamentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_medicamentLayout.createSequentialGroup()
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_filtrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(12, 12, 12)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_medicamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(den_medicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_medicamentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(162, 162, 162))))
        );

        jLabel19.getAccessibleContext().setAccessibleName("labelimaginemedicament");

        jLabel10.setText("Email:");

        jLabel11.setText("Parola:");

        jButton9.setBackground(new java.awt.Color(132, 215, 241));
        jButton9.setText("Adauga");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel12.setText("Rol:");

        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Gestionar", "Farmacist", " " }));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/utilizator.png"))); // NOI18N

        javax.swing.GroupLayout pnl_utilizatorLayout = new javax.swing.GroupLayout(pnl_utilizator);
        pnl_utilizator.setLayout(pnl_utilizatorLayout);
        pnl_utilizatorLayout.setHorizontalGroup(
            pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_utilizatorLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_utilizatorLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_utilizatorLayout.createSequentialGroup()
                        .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rol, 0, 97, Short.MAX_VALUE)
                            .addComponent(parola)
                            .addComponent(email))
                        .addGap(349, 349, 349))
                    .addGroup(pnl_utilizatorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_utilizatorLayout.setVerticalGroup(
            pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_utilizatorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_utilizatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton15.setBackground(new java.awt.Color(220, 147, 147));
        jButton15.setText("Vanzare");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/vanzare.png"))); // NOI18N

        javax.swing.GroupLayout panel_vanzareLayout = new javax.swing.GroupLayout(panel_vanzare);
        panel_vanzare.setLayout(panel_vanzareLayout);
        panel_vanzareLayout.setHorizontalGroup(
            panel_vanzareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_vanzareLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(panel_vanzareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_medicament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(112, 112, 112)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_vanzareLayout.setVerticalGroup(
            panel_vanzareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_vanzareLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_vanzareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(panel_vanzareLayout.createSequentialGroup()
                        .addComponent(cmb_medicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton15)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        menu.setText("Menu");

        jMenuItem1.setText("Client");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);

        jMenuItem2.setText("Medicament");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem2);

        menu_utilizator.setText("Adaugare Utilizator");
        menu_utilizator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_utilizatorActionPerformed(evt);
            }
        });
        menu.add(menu_utilizator);

        jMenuItem3.setText("Vanzare");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem3);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(pnl_autentificare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnl_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(pnl_medicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_utilizator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_vanzare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_autentificare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_medicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(pnl_utilizator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_vanzare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rolActionPerformed

    
    //LOGARE -- PENTRU FIECARE ROL
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        ResultSet rs = null;
        PreparedStatement pst = null;
        String sql = "select * from autentificare where Email = ? and Parola = ? and Rol = ? ";
        try {
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, txt_email.getText());
            pst.setString(2, txt_parola.getText());
            pst.setString(3, cmb_rol.getSelectedItem().toString());
           
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Autentificare cu succes!");
                pnl_autentificare.setVisible(false);
                txt_email.setText("");
                txt_parola.setText("");
                menu.setEnabled(true);
                
                rolAutentificare = cmb_rol.getSelectedItem().toString(); //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                
                 if(rolAutentificare.equals("Manager")){
                   jMenuItem1.setEnabled(true);
                   jMenuItem2.setEnabled(true);
                   menu_utilizator.setEnabled(true);
                 
               }else if(rolAutentificare.equals("Farmacist")){
                   jMenuItem1.setEnabled(true);
                   jMenuItem2.setEnabled(true);
                   menu_utilizator.setEnabled(false);
                  } else {
                   jMenuItem1.setEnabled(false);
                   jMenuItem2.setEnabled(true);
                   menu_utilizator.setEnabled(false);
               
                       
               }
                        
                
      
            } else {
                JOptionPane.showMessageDialog(null, "User sau parola gresite !");
                 txt_email.setText("");
                 txt_parola.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      pnl_client.setVisible(true);
      pnl_medicament.setVisible(false);
      pnl_utilizator.setVisible(false);
      afisareClient();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //ADAUGARE CLIENT
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
           try {
        
            java.sql.PreparedStatement ps = conn.prepareStatement("insert into client"  + " (nume,prenume,varsta,sex) "+ "values(?,?,?,?)");
            ps.setString(1, txt_nume.getText());
            ps.setString(2, txt_prenume.getText());
            ps.setString(3, txt_varsta.getText());
            ps.setString(4, txt_sex.getText());
         
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Clientul a fost adaugat cu succes!");
            txt_nume.setText("");
            txt_prenume.setText("");
            txt_varsta.setText("");
            txt_sex.setText("");
           
            afisareClient();
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_clientiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_clientiMouseClicked
       
        
       DefaultTableModel model = (DefaultTableModel)tabel_clienti.getModel();
       int selectedRowIndex = tabel_clienti.getSelectedRow();
        
       
       idClient = model.getValueAt(selectedRowIndex, 0).toString();
       txt_nume.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txt_prenume.setText(model.getValueAt(selectedRowIndex, 2).toString());
       txt_varsta.setText(model.getValueAt(selectedRowIndex, 3).toString());
       txt_sex.setText(model.getValueAt(selectedRowIndex, 4).toString());
     
      
        
    }//GEN-LAST:event_tabel_clientiMouseClicked

    //MODIFICARE CLIENT
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        try  {
              
           
     
            String nume = txt_nume.getText();
            String prenume = txt_prenume.getText();
            String varsta = txt_varsta.getText();
            String sex = txt_sex.getText();
          
       
      
            String query = "update client set nume = ?, prenume =?, varsta=?,  sex=?  where codc = ?";
            java.sql.PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, nume);
            preparedStmt.setString(2, prenume);
            preparedStmt.setString(3, varsta);
            preparedStmt.setString(4, sex);
            preparedStmt.setString(5, idClient);
            preparedStmt.executeUpdate();
            
            txt_nume.setText("");
            txt_prenume.setText("");
            txt_varsta.setText("");
            txt_sex.setText("");
          
            afisareClient();
      
         JOptionPane.showMessageDialog(null, "Clientul  a fost modificat!");
           }
         catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }  catch (SQLException ex) {
                   Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
             }
          
         
         
            
            
           

          
            
        
            
     
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    //STERGE CLIENT
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
        
            String message = " Sunteti sigur ?";
       
          int reply = JOptionPane.showConfirmDialog(null, message, "Confirmare", JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION) {
               
          try {
              
            String sql = "DELETE FROM client WHERE codc = ?";
            java.sql.PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, idClient);
            statement.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
            txt_nume.setText("");
            txt_prenume.setText("");
            txt_varsta.setText("");
            txt_sex.setText("");
          
            afisareClient();
            JOptionPane.showMessageDialog(null, "Clientul  a fost sters!");
            
            } 
        
        
        
        
        
        
        
            
     
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        pnl_medicament.setVisible(true);
        pnl_client.setVisible(false);
        pnl_utilizator.setVisible(false);
        afisareMedicament();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //ADAUGARE MEDICAMENT
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        
        
           try {
        
            java.sql.PreparedStatement ps = conn.prepareStatement("insert into medicament"  + " (denumire,pret,stoc,producator) "+ "values(?,?,?,?)");
            ps.setString(1, txt_denumire.getText());
            ps.setString(2, txt_pret.getText());
            ps.setString(3, jTextField1.getText());
            ps.setString(4, jTextField2.getText());
         
         
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Medicamentul a fost adaugat cu succes!");
            txt_denumire.setText("");
            txt_pret.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
            afisareMedicament();
           
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    //CAUTARE MEDICAMENT dupa DENUMIRE
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        
        ResultSet rs = null;
        java.sql.PreparedStatement pst = null;
        String sql = "select * from medicament where Denumire = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_cautare.getText().toString());
            rs = pst.executeQuery();
            tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void menu_utilizatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_utilizatorActionPerformed
        pnl_utilizator.setVisible(true);
        pnl_client.setVisible(false);
        pnl_medicament.setVisible(false);
        panel_vanzare.setVisible(false);
    }//GEN-LAST:event_menu_utilizatorActionPerformed

    //ADAUGARE UTILIZATOR
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        
        
          try {
        
            java.sql.PreparedStatement ps = conn.prepareStatement("insert into autentificare"  + " (Email,Parola,Rol) "+ "values(?,?,?)");
            ps.setString(1, email.getText());
            ps.setString(2, parola.getText());
            ps.setString(3, rol.getSelectedItem().toString());
         
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Utilizatorul a fost adaugat cu succes!");
            email.setText("");
            parola.setText("");
          
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    //MODIFICARE MEDICAMENT
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        
        
          try  {
              
           
     
            String denumire = txt_denumire.getText();
            String pret = txt_pret.getText();
            String stoc = jTextField1.getText();
            String producator = jTextField2.getText();
           
          
       
      
            String query = "update medicament set Denumire = ?, Pret =?, Stoc =?, Producator =? where idMedicament = ?";
            java.sql.PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, denumire);
            preparedStmt.setString(2, pret);
            preparedStmt.setString(3, stoc);
            preparedStmt.setString(4, producator);
            preparedStmt.setString(5, idMedicament);
            preparedStmt.executeUpdate();
            
            txt_denumire.setText("");
            txt_pret.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
          
          
            afisareMedicament();
      
         JOptionPane.showMessageDialog(null, "Medicamentul a fost modificat!");
           }
         catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }  catch (SQLException ex) {
                   Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
             }
          
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    
    private void tabel_medicamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_medicamentMouseClicked
      
        
          
       DefaultTableModel model = (DefaultTableModel)tabel_medicament.getModel();
       int selectedRowIndex = tabel_medicament.getSelectedRow();
        
       
       idMedicament = model.getValueAt(selectedRowIndex, 0).toString();
       txt_denumire.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txt_pret.setText(model.getValueAt(selectedRowIndex, 2).toString());
       jTextField1.setText(model.getValueAt(selectedRowIndex, 3).toString());
       jTextField2.setText(model.getValueAt(selectedRowIndex, 4).toString());
     
        
        
        
        
    }//GEN-LAST:event_tabel_medicamentMouseClicked

//STERGERE MEDICAMENT
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        
        
           String message = " Sunteti sigur ?";
       
          int reply = JOptionPane.showConfirmDialog(null, message, "Confirmare", JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION) {
               
          try {
              
            String sql = "DELETE FROM medicament WHERE idMedicament = ?";
            java.sql.PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, idMedicament);
            statement.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
            txt_denumire.setText("");
            txt_pret.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
            
          
            afisareMedicament();
            JOptionPane.showMessageDialog(null, "Medicamentul  a fost sters!");
            
            } 
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed


    
    //EXPORT TXT
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        
         String filePath = "C:\\Users\\MyPC\\Desktop\\BD P\\FarmacieProiect\\Farmacie\\txtfile.txt"; 
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tabel_medicament.getRowCount(); i++){
                for(int j = 0; j < tabel_medicament.getColumnCount(); j++){
                    bw.write(tabel_medicament.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
          
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    //FILTRARE Pret ASCENDENT
    public void afisarePretAscendent(){
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select pret as 'Pret' , denumire as 'Denumire' "
                    + " from medicament order by pret asc;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //FILTRARE IN FUNCTIE DE STOC (de la cel mai mare la cel mai mic---DESCENDENT, ASCENDENT--denumire)
     public void afisareStoc(){
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select stoc as 'Stoc', denumire as 'Denumire'"
                    + " from medicament order by stoc asc;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     
     //FILTRARE PRODUCATOR
    public void afisareProducator(){
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select producator as 'Producator', denumire as 'Denumire'"
                    + " from medicament order by producator desc;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //FILTRARE PRET DESCENDENT
     public void afisarePretDescendent(){
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select pret as 'Pret', denumire as 'Denumire' "
                    + " from medicament order by pret desc;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void cmb_filtrareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_filtrareMouseClicked
      
     
    }//GEN-LAST:event_cmb_filtrareMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
          
        if(cmb_filtrare.getSelectedItem().toString().equals("Pret mai mic")){
            afisarePretAscendent();
        }else if(cmb_filtrare.getSelectedItem().toString().equals("Pret mai mare")){
            afisarePretDescendent();
        }else if(cmb_filtrare.getSelectedItem().toString().equals("Stoc")){
            afisareStoc();
        }else if(cmb_filtrare.getSelectedItem().toString().equals("Producator")){
            afisareProducator();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    
    
    
    //EXPORT PDF
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     
 


              Document my_pdf_report = new Document();
        try {
            PdfWriter.getInstance(my_pdf_report, new FileOutputStream("pdf_farmacie.pdf"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
                my_pdf_report.open();            
                
                PdfPTable my_report_table = new PdfPTable(4);
               
                PdfPCell table_cell;
                
                
               ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select Denumire as 'Denumire' , Pret as 'Pret', Stoc as 'Stoc' , Producator as 'Producator' " + " from medicament;";
        try {
            pst = conn.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs = pst.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
               
                
        try {
            while(rs.next()){
                
                String denumire = rs.getString("Denumire");
                table_cell = new PdfPCell(new Phrase(denumire));
                my_report_table.addCell(table_cell);
                String pret = rs.getString("Pret");
                table_cell=new PdfPCell(new Phrase(pret));
                my_report_table.addCell(table_cell);
                String stoc = rs.getString("Stoc");
                table_cell=new PdfPCell(new Phrase(stoc));
                my_report_table.addCell(table_cell);
                String producator = rs.getString("Producator");
                table_cell=new PdfPCell(new Phrase(producator));
                my_report_table.addCell(table_cell);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
                           
            my_pdf_report.add(my_report_table);
        } catch (DocumentException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
                my_pdf_report.close();
                
        try {
           
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        /*try {               
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
        } */










        
    }//GEN-LAST:event_jButton12ActionPerformed

    // EXPORT EXCEL----file.xls
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      
       
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/farmacie", "root", "root");
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("file.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Sheet 0");
            HSSFRow row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("Pret");
            row1.createCell(1).setCellValue("Denumire");
            row1.createCell(2).setCellValue("Stoc");
            row1.createCell(3).setCellValue("Producator");
            HSSFRow  row2 ;
            ResultSet rs = statement.executeQuery("SELECT Denumire, Pret, Stoc, Producator FROM medicament");
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
            System.out.println("Export Success");
        }catch(ClassNotFoundException e){
            System.out.println(e);
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }

    
       
       
       
    }//GEN-LAST:event_jButton13ActionPerformed

    
 

    
    
  
  //CALENDAR    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                
DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();



SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");

   String dataStart = dateFormat.format(jDateChooser1.getDate());
   String dataFinal = dateFormat.format(jDateChooser2.getDate());
   String denumire_medicament = den_medicament.getText().toString();
  
  System.out.println(dataStart);
  System.out.println(dataFinal); 
  System.out.println(denumire_medicament);
  try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "SELECT COUNT(m.idMedicament)  FROM medicament m , vanzare v where m.idMedicament = v.idMedicament AND  v.dataVanzare  between '" + dataStart + '"'+"' AND '" + dataFinal + '"' + "' AND '"+ " m.Denumire = " + denumire_medicament + "';";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
           
             while(rs.next()){

           int pret = rs.getInt("count(m.idMedicament)");
           System.out.println(pret);
           my_bar_chart_dataset.setValue(pret, denumire_medicament, "Nr Produse Vandute");
           
           
            }
            JFreeChart chart = ChartFactory.createBarChart("Student’s Score", "Student’s Name","Nr", my_bar_chart_dataset, PlotOrientation.VERTICAL,true,true,false);

CategoryPlot p = chart.getCategoryPlot();

ChartFrame frame = new ChartFrame("Bar Chart Report",chart);

frame.setVisible(true);

frame.setSize(650,550);

            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
  
  
  
  
//DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();
//           
//try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://goskynet.ddns.net/farmacie","root","root");
//            Statement statement = con.createStatement();
//                        
//   String dataStart = dateFormat.format(jDateChooser1.getDate());
//   String dataFinal = dateFormat.format(jDateChooser2.getDate());
//  String denumire_medicament = den_medicament.getText().toString();
//  
//  System.out.println(dataStart);
//  System.out.println(dataFinal); 
//  System.out.println(denumire_medicament);
//            
//            
//          // ResultSet rs = statement.executeQuery("SELECT sum(m.idMedicament) FROM medicament m , vanzare v where m.idMedicament = v.idMedicament and dataVanzare between '"+dataStart+'"'+"' AND '"+dataFinal+'"'+"';");
//           ResultSet rs3 = statement.executeQuery("SELECT COUNT(m.idMedicament)  FROM medicament m , vanzare v where m.idMedicament = v.idMedicament AND  v.dataVanzare  between '" + dataStart + '"'+"' AND '" + dataFinal + '"' + "' AND '"+ " m.Denumire = " + denumire_medicament + "'");
//          // ResultSet rs4 = statement.executeQuery("SELECT count(m.idMedicament)  FROM medicament m , vanzare v where m.idMedicament = v.idMedicament AND  Denumire = '"+denumire_medicament+"';");
//          // ResultSet rs5 = statement.executeQuery("SELECT count(m.idMedicament)  FROM medicament m , vanzare v where m.idMedicament = v.idMedicament AND  m.Denumire =  '"+denumire_medicament+'"'+"' AND v.dataVanzare between '" +dataStart+'"'+"' AND '"+dataFinal+"';");
//
//          
//          
//             while(rs3.next()){
//
//           int pret = rs3.getInt("count(m.idMedicament)");
//           System.out.println(pret);
//           my_bar_chart_dataset.setValue(pret, denumire_medicament, "Nr Produse Vandute");
//           
//           
//            }
//            
//             rs3.close();
           
// JFreeChart chart = ChartFactory.createBarChart("Student’s Score", "Student’s Name","Nr", my_bar_chart_dataset, PlotOrientation.VERTICAL,true,true,false);
//
//CategoryPlot p = chart.getCategoryPlot();
//
//ChartFrame frame = new ChartFrame("Bar Chart Report",chart);
//
//frame.setVisible(true);
//
//frame.setSize(650,550);

//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//            e.printStackTrace();
//        }
        
      











        
              
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      
        pnl_client.setVisible(false);
        pnl_medicament.setVisible(false);      
        pnl_utilizator.setVisible(false);
        panel_vanzare.setVisible(true);
        afisateMedicamente();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void afisateMedicamente(){
        
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "SELECT Denumire  FROM medicament";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
           
             while(rs.next()){

           cmb_medicament.addItem(rs.getString("Denumire"));
         
          
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public int getIdMedicament(){
        
        int idMedicament = 0 ;
        
          try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "SELECT idMedicament  FROM medicament where Denumire = '" + cmb_medicament.getSelectedItem().toString() + "';";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
           
             while(rs.next()){
             idMedicament = rs.getInt("idMedicament");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
          
           return idMedicament;
    }
    
    public String getProducator(){
          String producator = "" ;
  
        
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "SELECT Producator  FROM medicament where Denumire = '" + cmb_medicament.getSelectedItem().toString() + "';";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
           while(rs.next()){
            producator = rs.getString("Producator");
             
            }
        }
catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return producator;
    }
    
    
    public int getPretMedicament(){
        
        int pret = 0 ;
  
        
        try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "SELECT Pret  FROM medicament where Denumire = '" + cmb_medicament.getSelectedItem().toString() + "';";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
           while(rs.next()){
             pret = rs.getInt("Pret");
             
            }
        }
        
catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        return pret;
        
}
    


       
    
    //VANZARE--FACTURA--PDF
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       
        
        String data  = new SimpleDateFormat("dd.MM.yyyy").format(Calendar.getInstance().getTime());
        
        try {
        
            java.sql.PreparedStatement ps = conn.prepareStatement("insert into vanzare"  + " (idMedicament,dataVanzare) "+ "values(?,?)");
            ps.setInt(1, getIdMedicament());
            ps.setString(2, data);
            ps.executeUpdate();
  
            JOptionPane.showMessageDialog(null, "Produs vandut cu succes!");
           
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
        
        
        String medicament = cmb_medicament.getSelectedItem().toString();
        
        
        JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File("" +""+ ""+"Factura"+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
        try {
         
           Document myDocument = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
           myDocument.open();
           
           myDocument.add(new Paragraph("Factura",FontFactory.getFont(FontFactory.TIMES_BOLD,20,java.awt.Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add((new Paragraph("Medicament",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,java.awt.Font.BOLD))));
           myDocument.add(new Paragraph("Denumire medicament: "+medicament,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,java.awt.Font.BOLD)));
           myDocument.add(new Paragraph("Data: "+data,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,java.awt.Font.BOLD)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
          
           myDocument.add(new Paragraph("TOTAL PLATA",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,java.awt.Font.BOLD)));
           myDocument.add(new Paragraph("Pret: " +getPretMedicament()+" Lei",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,java.awt.Font.BOLD)));
           myDocument.add(new Paragraph("Producator: " +getProducator(),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,java.awt.Font.BOLD)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
          
           myDocument.newPage();
           myDocument.close();  
           JOptionPane.showMessageDialog(null,"Raportul a fost generat cu success!");
           
     }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
         
     }
     finally {
            
            try{
            
                
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
            }
     }
        
      
            } 
    }//GEN-LAST:event_jButton15ActionPerformed

    //CAUTARE CLIENTI(dupa nume)
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
          ResultSet rs = null;
        java.sql.PreparedStatement pst = null;
        String sql = "select * from client where Nume = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextField3.getText().toString());
            rs = pst.executeQuery();
            tabel_clienti.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    
                                             

    }//GEN-LAST:event_jButton16ActionPerformed



    
    //IMPORT EXCEL
   public void importExcelToJtableJava() {

       File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportToJTable = null;
        String defaultCurrentDirectoryPath = "C:\\Users\\MyPC\\Desktop\\New folder";
        JFileChooser excelFileChooser = new JFileChooser(defaultCurrentDirectoryPath);
        excelFileChooser.setDialogTitle("Select Excel File");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = excelFileChooser.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportToJTable = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportToJTable.getSheetAt(0);
                boolean amp;
 
                for (int row = 0; row < excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);
 
                    XSSFCell excelName = excelRow.getCell(0);
                    XSSFCell excelGender = excelRow.getCell(1);
                    XSSFCell excelProgrammingLanguage = excelRow.getCell(2);
                    XSSFCell excelSubject = excelRow.getCell(3);
                    XSSFCell excelImage = excelRow.getCell(4);
 
                           DefaultTableModel model = (DefaultTableModel)tabel_medicament.getModel();

                    JLabel excelJL = new JLabel(new ImageIcon(new ImageIcon(excelImage.getStringCellValue()).getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH)));
                    model.addRow(new Object[]{excelName, excelGender, excelProgrammingLanguage, excelSubject, excelJL});
                }
                JOptionPane.showMessageDialog(null, "Imported Successfully !!.....");
            } catch (IOException iOException) {
                JOptionPane.showMessageDialog(null, iOException.getMessage());
            } finally {
                try {
                    if (excelFIS != null) {
                        excelFIS.close();
                    }
                    if (excelBIS != null) {
                        excelBIS.close();
                    }
                    if (excelImportToJTable != null) {
                        excelImportToJTable.close();
                    }
                } catch (IOException iOException) {
                    JOptionPane.showMessageDialog(null, iOException.getMessage());
                }
            }
        }
    }  



    
    //BAR_CHART
    public void afisareMedicament(){
        
        
         DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();
        
           try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select idMedicament as 'idMedicament',denumire as 'Denumire',pret as 'Pret', stoc as 'Stoc' , producator as 'Producator'"
                    + " from medicament;";
            pst = conn.prepareStatement(sql);
          
           
            rs = pst.executeQuery(sql);
            
             tabel_medicament.setModel(DbUtils.resultSetToTableModel(rs));
        
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           
 
           
}
    
    public void afisareClient(){
         try {
            
            ResultSet rs = null;
            java.sql.PreparedStatement pst = null;
            String sql = "select codc as 'Codc', nume as 'Nume',prenume as 'Prenume',varsta as 'Varsta',"
                    + " sex as 'Sex'"
                    + " from client;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabel_clienti.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_filtrare;
    private javax.swing.JComboBox<String> cmb_medicament;
    private javax.swing.JComboBox<String> cmb_rol;
    private javax.swing.JTextField den_medicament;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menu_utilizator;
    private javax.swing.JPanel panel_vanzare;
    private javax.swing.JTextField parola;
    private javax.swing.JPanel pnl_autentificare;
    private javax.swing.JPanel pnl_client;
    private javax.swing.JPanel pnl_medicament;
    private javax.swing.JPanel pnl_utilizator;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTable tabel_clienti;
    private javax.swing.JTable tabel_medicament;
    private javax.swing.JTextField txt_cautare;
    private javax.swing.JTextField txt_denumire;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nume;
    private javax.swing.JPasswordField txt_parola;
    private javax.swing.JTextField txt_prenume;
    private javax.swing.JTextField txt_pret;
    private javax.swing.JTextField txt_sex;
    private javax.swing.JTextField txt_varsta;
    // End of variables declaration//GEN-END:variables
}
